### ISSUE TITLE
podspec file

### ISSUE THREAD

**Issue by stany-bluebik** [SEAbdulbasit/TravelApp-KMP#2]
No podspec file in the project. Can't perform pod install

**Comment by ercanduman** [comment]
I also tried this project and it gives an error while installing the **pod**.

**Details:** 
```
'pod install' command failed with code 1.
Full command: pod install
```

**Here you can find full logs:**

> Execution failed for task ':shared:podInstall'.
> 'pod install' command failed with code 1.
  Full command: pod install
  Error message:
  Analyzing dependencies
  ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
  ### Command
  ```
  /Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod install
  ```
  ### Report
  * What did you do?
  * What did you expect to happen?
  * What happened instead?
  ### Stack
  ```
     CocoaPods : 1.5.2
          Ruby : ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin15]
      RubyGems : 2.6.8
          Host : macOS 14.2.1 (23C71)
         Xcode : 15.2 (15C500b)
           Git : git version 2.6.2
  Ruby lib dir : /Applications/CocoaPods.app/Contents/Resources/bundle/lib
  Repositories : 
  ```
  ### Plugins
  ```
  cocoapods-check           : 1.0.0
  cocoapods-deintegrate     : 1.0.2
  cocoapods-plugins         : 1.0.0
  cocoapods-plugins-install : 0.0.1
  cocoapods-search          : 1.0.0
  cocoapods-stats           : 1.0.0
  cocoapods-trunk           : 1.3.0
  cocoapods-try             : 1.1.0
  ```
  ### Podfile
  ```ruby
  target 'iosApp' do
    use_frameworks!
    platform :ios, '14.1'
    pod 'shared', :path => '../shared'
  end
  ```
  ### Error
  ```
  RuntimeError - [Xcodeproj] Unknown object version.
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:218:in `initialize_from_file'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:103:in `open'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:918:in `block (2 levels) in inspect_targets_to_integrate'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:917:in `each'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:917:in `block in inspect_targets_to_integrate'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:912:in `inspect_targets_to_integrate'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:243:in `analyze'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:116:in `install!'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/command/install.rb:41:in `run'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
  /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
  /Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:22:in `load'
  /Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:22:in `<main>'
  ```

**Comment by ercanduman** [comment]
Running the following commands in Terminal in the given order resolved the issue for me 🚀 

```bash
chmod 600 ~/.netrc
sudo arch -x86_64 gem install ffi
```

And finally, within the **`iosApp`** folder of the KMM project, I ran:

```bash
arch -x86_64 pod install
```

ℹ️ If you encounter any further issues related to **CocoaPods**, you can refer to the following solution:
[https://stackoverflow.com/questions/64901180/how-to-run-cocoapods-on-apple-silicon-m1/66556339#66556339](https://stackoverflow.com/questions/64901180/how-to-run-cocoapods-on-apple-silicon-m1/66556339#66556339)
